export const actionTypes = {
    FETCH_API : "FETCH_API",
    SEND_FILTERS : "SEND_FILTERS",
    PRODUCT_DESCRIPTION:"PRODUCT_DESCRIPTION",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_ITEM:"REMOVE_ITEM",
    PLUS_QUANTITY:"PLUS_QUNATITY",
    MINUS_QUANTITY:"MINUS_QUANTITY",
    PROFILE_CREDENTIALS:"PROFILE_CREDENTIALS"
} 